#!/bin/bash
# 🚀 AAPDA Vision AI - GETTING STARTED CHECKLIST
# ===============================================
# Follow these steps to get the project running

echo "🚀 AapdaVision AI - Getting Started"
echo "===================================="
echo ""

# Step 1: Check Prerequisites
echo "Step 1: Checking Prerequisites..."
echo "✓ Python 3.10+ installed: $(python --version 2>/dev/null || echo 'NOT FOUND')"
echo "✓ Node.js 16+ installed: $(node --version 2>/dev/null || echo 'NOT FOUND')"
echo ""

# Step 2: Backend Setup
echo "Step 2: Backend Setup Instructions"
echo "----------------------------------"
echo "📁 Navigate to backend directory:"
echo "   cd backend"
echo ""
echo "🔧 Create virtual environment:"
echo "   python -m venv .venv"
echo "   source .venv/bin/activate  # On Windows: .venv\Scripts\activate"
echo ""
echo "📦 Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "🗄️  Create .env file:"
echo "   cat > .env << EOF"
echo "   FLASK_ENV=development"
echo "   DATABASE_URL=sqlite:///aapda_vision_ai.db"
echo "   PORT=5000"
echo "   UPLOAD_FOLDER=data/uploads"
echo "   OUTPUT_FOLDER=data/outputs"
echo "   EOF"
echo ""
echo "🚀 Run backend server:"
echo "   python app.py"
echo ""
echo "Expected Output:"
echo "   * Serving Flask app 'app'"
echo "   * Running on http://0.0.0.0:5000"
echo "   ✓ Model loaded successfully"
echo "   ✓ NGOs loaded: 6 NGOs"
echo ""

# Step 3: Frontend Setup
echo "Step 3: Frontend Setup Instructions"  
echo "----------------------------------"
echo "📁 In a NEW TERMINAL, navigate to frontend:"
echo "   cd frontend"
echo ""
echo "📦 Install dependencies:"
echo "   npm install"
echo ""
echo "🚀 Run frontend dev server:"
echo "   npm run dev"
echo ""
echo "Expected Output:"
echo "   > next dev"
echo "   - ready started server on 0.0.0.0:3000, url: http://localhost:3000"
echo ""

# Step 4: Test the System
echo "Step 4: Test the System"
echo "----------------------"
echo "🌐 Open browser: http://localhost:3000"
echo ""
echo "📸 Upload Test Image:"
echo "   1. Click 'Upload Image' or drag an image"
echo "   2. Enter latitude/longitude (or use GPS auto-detect)"
echo "   3. Click 'Analyze Disaster Image'"
echo ""
echo "✅ Expected Results:"
echo "   - Damage percentage displayed"
echo "   - Severity gauge shown (Green/Yellow/Red)"
echo "   - SHAP explanation visualization"
echo "   - Assigned NGO displayed"
echo "   - Alert status shown if damage > 60%"
echo ""

# Step 5: View Disaster Logs
echo "Step 5: View Disaster Logs"
echo "--------------------------"
echo "📊 Click on 'Disaster Logs' page:"
echo "   - See all analysis records in a table"
echo "   - Filter by risk level (Low/Medium/High)"
echo "   - Sort by newest/oldest/damage percentage"
echo "   - Click rows to see detailed information"
echo "   - Download reports for each disaster"
echo ""

# Step 6 API Testing
echo "Step 6: Test APIs with curl"
echo "---------------------------"
echo ""
echo "Test Health Check:"
echo "   curl http://localhost:5000/health"
echo ""
echo "Test Prediction (POST):"
echo "   curl -X POST http://localhost:5000/api/predict \\"
echo "     -F 'image=@/path/to/image.jpg' \\"
echo "     -F 'latitude=28.6139' \\"
echo "     -F 'longitude=77.2090' \\"
echo "     -F 'location_name=Delhi'"
echo ""
echo "Get All Logs (GET):"
echo "   curl http://localhost:5000/api/logs"
echo ""
echo "Get Heatmap Data (GET):"
echo "   curl http://localhost:5000/api/heatmap-data"
echo ""
echo "Get ML Insights (GET):"
echo "   curl http://localhost:5000/api/ml-insights"
echo ""
echo "Get Campaigns (GET):"
echo "   curl http://localhost:5000/api/campaigns"
echo ""

# Step 7 Integration with Your Model
echo "Step 7: Use Your Trained Model"
echo "------------------------------"
echo "⚙️  To use your actual trained model:"
echo ""
echo "1. Copy your trained model:"
echo "   cp /path/to/your/model.pkl backend/models/damage_classifier.pkl"
echo ""
echo "2. Optional - Also provide scaler if you have one:"
echo "   cp /path/to/your/scaler.pkl backend/models/damage_classifier_scaler.pkl"
echo ""
echo "3. Restart backend:"
echo "   Kill the running backend and restart with: python app.py"
echo ""
echo "4. System will automatically load your model!"
echo ""

# Step 8 Update NGO Data
echo "Step 8: Update NGO Data (Optional)"
echo "---------------------------------"
echo "📋 Edit NGO dataset:"
echo "   vim backend/data/ngo_dataset.json"
echo ""
echo "or"
echo ""
echo "   Update database directly through API (coming soon)"
echo ""
echo "Fields to update for each NGO:"
echo "  - name: Organization name"
echo "  - latitude/longitude: Headquarters location"
echo "  - contact_email: Emergency contact"
echo "  - specialization: Medical/Relief/Search"
echo "  - service_radius_km: Operating area"
echo ""

# File Structure
echo ""
echo "Step 9: Verify File Structure"
echo "-----------------------------"
echo "📁 Project should have:"
echo ""
echo "backend/"
echo "  ├── services/"
echo "  │   ├── ml_pipeline.py          ✅ NEW"
echo "  │   ├── ngo_service.py          ✅ NEW"
echo "  │   ├── analysis_service.py     (existing)"
echo "  │   └── ..."
echo "  ├── routes/"
echo "  │   ├── predict.py              ✅ NEW"
echo "  │   ├── analyze.py              (existing)"
echo "  │   └── ..."
echo "  ├── models/"
echo "  │   ├── damage_model.py         ✅ UPDATED"
echo "  │   ├── damage_classifier.pkl   (add your model here)"
echo "  │   └── ..."
echo "  ├── data/"
echo "  │   ├── ngo_dataset.json        ✅ NEW"
echo "  │   ├── uploads/                (auto-created)"
echo "  │   ├── outputs/                (auto-created)"
echo "  │   └── ..."
echo "  └── app.py                      ✅ UPDATED"
echo ""
echo "frontend/"
echo "  ├── components/"
echo "  │   ├── DamageGauge.js          ✅ NEW"
echo "  │   ├── DamageGauge.module.css  ✅ NEW"
echo "  │   ├── DisasterLogs.js         ✅ NEW"
echo "  │   ├── DisasterLogs.module.css ✅ NEW"
echo "  │   ├── SHAPExplainer.js        ✅ NEW"
echo "  │   ├── SHAPExplainer.module.css✅ NEW"
echo "  │   ├── UploadAnalyzer.enhanced.js ✅ NEW"
echo "  │   ├── TeamSection.js          ✅ VERIFIED (only 2 members)"
echo "  │   └── ..."
echo "  └── ..."
echo ""

# Troubleshooting
echo "Step 10: Troubleshooting"
echo "-----------------------"
echo ""
echo "Problem: 'Module not found' errors"
echo "Solution:"
echo "  pip install -r requirements.txt --force-reinstall"
echo ""
echo "Problem: 'Cannot connect to backend'"
echo "Solution:"
echo "  - Ensure backend running on port 5000: curl http://localhost:5000/health"
echo "  - Check firewall settings"
echo "  - Verify CORS is enabled (it is by default)"
echo ""
echo "Problem: 'Database locked' errors"
echo "Solution:"
echo "  rm backend/aapda_vision_ai.db"
echo "  # Restart backend"
echo ""
echo "Problem: 'GPU out of memory'"
echo "Solution:"
echo "  - Not using GPU in current implementation"
echo "  - Should run fine on CPU"
echo ""

# Resources
echo ""
echo "📚 Additional Resources"
echo "=======================" 
echo "- IMPLEMENTATION_GUIDE.md  : Detailed setup and API docs"
echo "- README_IMPLEMENTATION.md : Project overview"
echo "- IMPLEMENTATION_COMPLETE.py : Status and statistics"
echo ""
echo "🎓 For Academic Presentations"
echo "=============================="
echo "1. Explain the feature extraction pipeline (70D image vectors)"
echo "2. Describe SHAP values (why each feature matters)"
echo "3. Show NGO linking algorithm (Haversine + priority scoring)"
echo "4. Demonstrate data normalization and scaling"
echo "5. Explain database design (normalized schema)"
echo ""

# Success
echo ""
echo "✅ READY TO GO!"
echo "==============="
echo ""
echo "Next Steps:"
echo "1. ✅ Backend running on http://localhost:5000"
echo "2. ✅ Frontend running on http://localhost:3000"  
echo "3. 📸 Upload a test image"
echo "4. 🎯 See predictions, SHAP, and NGO assignment"
echo "5. 📊 View disaster logs table"
echo "6. 🚀 Deploy to production!"
echo ""
echo "Good luck! 🎉"
